2018-11-27T19:11:32|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\measurement.py", line 25, in run
    self.measurement._thread_run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\measurement.py", line 179, in _thread_run
    self.run()
  File "C:\LabPrograms\Python\Camera-ScopeFoundry\CameraMeasurement.py", line 187, in run
    if total > self.settings['threshold']:
UnboundLocalError: local variable 'total' referenced before assignment

