2018-12-05T10:23:05|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\measurement.py", line 25, in run
    self.measurement._thread_run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\measurement.py", line 179, in _thread_run
    self.run()
  File "C:\LabPrograms\Python\Camera-ScopeFoundry\CameraMeasurement.py", line 145, in run
    self.camera.hamamatsu.stopRecording()
  File "C:\LabPrograms\Python\Camera-ScopeFoundry\CameraDevice.py", line 1281, in stopRecording
    if paramrecstatus.value == DCAMCAP_STATUS_BUSY:
AttributeError: 'DCAMREC_STATUS' object has no attribute 'value'

