2018-11-15T10:26:29|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\Camera-ScopeFoundry\CameraApp.py", line 26, in <module>
    app = HamamatsuApp(sys.argv)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\base_app.py", line 334, in __init__
    self.setup_default_ui()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\base_app.py", line 365, in setup_default_ui
    measure.setup_figure()
  File "C:\Users\Admin\Desktop\Camera-ScopeFoundry\CameraMeasurement.py", line 56, in setup_figure
    self.np_init = np.zeros([self.camera.subarrayh.val,self.camera.subarrayv.val])
TypeError: 'float' object cannot be interpreted as an integer

